name: Compile Test

on: [push, pull_request]

jobs:
  compile_job:
    name: Compile + Parser test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and Verify
        run: mvn -B verify
